//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Emp_id { get; set; }
        [Required]
        [RegularExpression("[A-Za-z]+", ErrorMessage = "Only alphabets.!")]
        public string Name { get; set; }
        [Required]
        [EmailAddress(ErrorMessage = "Invalid Email.!")]
        public string Email { get; set; }
        [Required]
        [RegularExpression(@"[9876]\d{9}", ErrorMessage = "Invalid Mobile no.")]
        public Nullable<long> Phone_No { get; set; }
       
        public string Address { get; set; }
        [Required]
        [Display(Name="State Name")]
        public Nullable<int> state_id { get; set; }
        [Required]
        [Display(Name = "City Name")]
        public Nullable<int> city_id { get; set; }
    
        public virtual city city { get; set; }
        public virtual state state { get; set; }
    }
}
